version: "3"

networks:
  local:

services:
  db:
    image: postgres:latest
    container_name: database
    env_file:
      - .env
    ports:
      - "5433:5433"
    volumes:
      - ./monitoring_bot/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      local:

  bot:
    build: .
    container_name: bot
    depends_on:
      - db
    env_file:
      - .env
    networks:
      local:
    restart: on-failure
